In [31]:
import numpy as np
arr1=np.zeros((2,3))
print(arr1, arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [32]:
arr2=np.ones((5,))
print(arr2, arr2.shape)

arr3=np.full((5,6), 100) # prefill this value
print(arr3, arr3.shape)

arr4=np.eye(3,3) # identity matrix
print(arr4, arr4.shape)

arr5=np.arange(1,11,2) # 1-10
print(arr5, arr5.shape)

arr6=np.linspace(1,100,4) # evenly spaced arrays
print(arr6)

[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]] (5, 6)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.]
