In [297]:
#1. Create an Array
# Create a NumPy array containing numbers from 1 to 10. Print:

# Array
# Data type
# Shape
# Number of dimensions
import numpy as np

arr=np.arange(1,11)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
int64
(10,)
1


In [298]:
#2. Mixed Data Types
import numpy as np
arr=np.array([1,2,3,4,5,'5'])
print(arr, arr.dtype)

['1' '2' '3' '4' '5' '5'] <U21


In [299]:
# 3. Print Even Numbers
import numpy as np
arr=np.arange(1,50)
print(arr[1:50:2])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [300]:
# 4. Print Odd Numbers
import numpy as np
arr=np.arange(1,50)
print(arr[0:50:2])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [301]:
# 5. Reverse an Array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [302]:
#6.  Indexing & Slicing
arr=np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0:3])
print(arr[4::])
print(arr[2:5:])
print(arr[1:2])

[10 20 30]
[50 60 70]
[30 40 50]
[20]


In [303]:
#7.Replace Elements
arr=np.array([10, 20, 30, 40, 50])
arr[arr>30]=0
print(arr)

[10 20 30  0  0]


In [304]:
#8. Find Maximum and Minimum
arr=np.array([23, 5, 67, 12, 89, 34])
print(np.min(arr))
print(np.max(arr))
print(np.argmax(arr)) #index
print(np.argmin(arr)) #index

5
89
4
1


In [305]:
# 9. Count Values
# Given an array, count how many numbers are:

# Greater than 50
# Less than 50
# Equal to 50
arr=np.array([10,20,30,50,60,70])

gt_50=np.sum(arr>50)
lt_50=np.sum(arr<50)
eq_50=np.sum(arr==50)

print(lt_50)
print(gt_50)
print(eq_50)

3
2
1


In [306]:
#10.  2D Arrays

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.shape[0]) # Number of row
print(arr.shape[1]) # Number of col

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
3
3


In [307]:
# Extract:50
# First row
# Last row
# First column
# Last column

arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr[1,1])
print(arr[0,:])
print(arr[-1,:])
print(arr[:,0])
print(arr[:,-1])

50
[10 20 30]
[70 80 90]
[10 40 70]
[30 60 90]


In [308]:
#12. Matrix Diagonal
arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(np.diag(arr))

[10 50 90]


In [309]:
#13. Row Sum
arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr.sum(axis=1))

[ 60 150 240]


In [310]:
#14. Col Sum
arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr.sum(axis=0))

[120 150 180]


In [311]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(a,b))

[3 4 5]
