In [4]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattend=arr.flatten()
print(flattend,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
